parameters:
    env(ROOT): "%env(HOME)%/.config/transmailifier"
    env(CONFIG): "%env(ROOT)%/config.yaml"

    # TODO: Symfony workaround
    kernel.secret: transmailifier

framework:
    mailer:
        dsn: '%env(string:key:url:key:mailer:yaml:file:CONFIG)%'
        envelope:
            sender: '%env(string:key:sender_address:key:mailer:yaml:file:CONFIG)%'
    serializer:
        mapping:
            paths:
                - "%kernel.project_dir%/config/serializer.yaml"

services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false
        bind:
            $readerConfig: "%env(key:reader:yaml:file:CONFIG)%"
            $storagePath: "%env(ROOT)%/transmailifier.sqlite"

    Dkarlovi\Transmailifier\:
        resource: '../src/Transmailifier'
